# Content-Type: application/json

###
GET http://localhost:3003/users

###
GET http://localhost:3003/users/admin

###
GET http://localhost:3003/users?name=fred

###
POST http://localhost:3003/users
Content-Type: application/json

{
    "id": 7,
    "name": "Camila",
    "email": "camila@email.com",
    "type": "NORMAL",
    "age": 30
}